name: headortails
description: An example application using Riverpod
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_riverpod: ^1.0.3
  shared_preferences: ^2.0.13

  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.10
  freezed: ^2.0.3
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true